# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      - /.github/actions
      - /.github/workflows
    schedule:
      interval: daily
    commit-message:
      prefix: deps(CI)
    labels:
      - CI
      - dependencies
    open-pull-requests-limit: 0 # https://stackoverflow.com/questions/64047526/how-to-get-dependabot-to-trigger-for-security-updates-only#comment123070708_68254421
  - package-ecosystem: nuget
    directory: /c#
    schedule:
      interval: daily
    commit-message:
      prefix: deps(c#)
    labels:
      - nuget
      - dependencies
    open-pull-requests-limit: 0
  - package-ecosystem: composer
    directory: /be
    exclude-paths:
     - /be/public/react-json-view
    schedule:
      interval: daily
    commit-message:
      prefix: deps(be)
    labels:
      - composer
      - dependencies
    open-pull-requests-limit: 0
  - package-ecosystem: npm
    directory: /be/public/react-json-view
    schedule:
      interval: daily
    commit-message:
      prefix: deps(react-json-view)
    labels:
      - yarn
      - dependencies
    open-pull-requests-limit: 0
  - package-ecosystem: npm
    directory: /fe
    schedule:
      interval: daily
    commit-message:
      prefix: deps(fe)
    labels:
      - yarn
      - dependencies
    open-pull-requests-limit: 0
