<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\shared\tbm.Shared.csproj" />
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="LanguageExt.Core" Version="4.4.9" />
        <PackageReference Include="Microsoft.Extensions.Http.Polly" Version="9.0.8" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL.NetTopologySuite" Version="10.0.0" />
        <PackageReference Include="OpenCvSharp4" Version="4.11.0.20250507" />
        <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.11.0.20250507" />
        <PackageReference Include="Sdcb.PaddleInference.runtime.win64.mkl" Version="3.1.0.54" />
        <PackageReference Include="Sdcb.PaddleOCR" Version="3.0.1" />
        <PackageReference Include="Sdcb.PaddleOCR.Models.Online" Version="3.0.1" />
        <PackageReference Include="SixLabors.ImageSharp" Version="3.1.11" />
        <PackageReference Include="System.IO.Hashing" Version="9.0.8" />
        <PackageReference Include="System.Threading.RateLimiting" Version="9.0.8" />
        <PackageReference Include="ThumbHash" Version="2.1.1" />
    </ItemGroup>
    <ItemGroup>
        <None Update="appsettings.Development.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="Never" />
        <None Update="appsettings.Production.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="Never" />
        <None Update="appsettings.json" CopyToOutputDirectory="PreserveNewest" />
        <None Update="nlog.config" CopyToOutputDirectory="PreserveNewest" />
    </ItemGroup>
</Project>
