# https://stackoverflow.com/questions/75318609/matrix-strategy-over-entire-workflow-in-github-actions/75337311#75337311
name: be
on:
  push:
    paths:
      - be/**
      - '!be/public/react-json-view/**'
      - .github/workflows/be*.yaml
      - .github/actions/be/action.yaml
jobs:
  runs-on:
    strategy:
      matrix:
        runs-on:
          - ubuntu-latest
          - windows-latest
          - macos-latest
      fail-fast: false
    uses: ./.github/workflows/be_base.yaml
    with:
      runs-on: ${{ matrix.runs-on }}
