name: fe/base
on:
  workflow_call:
    inputs:
      runs-on:
        required: true
        type: string
defaults:
  run:
    working-directory: fe
jobs:
  tsc:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/fe
      - run: yarn run vue-tsc -p .nuxt/tsconfig.app.json

  eslint:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/fe
      - run: yarn run eslint

  stylelint:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/fe

      - id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: ${{ github.workspace }}/fe/.stylelintcache
          key: ${{ runner.os }}-fe-stylelintcache
          restore-keys: ${{ runner.os }}-fe-stylelintcache-

      - uses: xt0rted/stylelint-problem-matcher@v1
      - id: firstStylelint
        run: yarn run stylelint --cache --custom-formatter stylelint-actions-formatters '**/*.vue'
      - if: always() && (steps.firstStylelint.outcome == 'success' || steps.firstStylelint.outcome == 'failure')
        run: yarn run stylelint --cache --custom-formatter stylelint-actions-formatters '**/*.css'

      - uses: actions/cache/save@v4
        if: always() && steps.cache-restore.outputs.cache-hit != 'true'
        with:
          path: ${{ github.workspace }}/fe/.stylelintcache
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}

  type-coverage:
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/fe

      - id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: ${{ github.workspace }}/fe/.type-coverage
          key: ${{ runner.os }}-fe-type-coverage
          restore-keys: ${{ runner.os }}-fe-type-coverage-

      # https://github.com/plantain-00/type-coverage/issues/145
      - run: yarn run type-coverage --show-relative-path --cache --detail --strict --at-least 95

      - uses: actions/cache/save@v4
        if: always() && steps.cache-restore.outputs.cache-hit != 'true'
        with:
          path: ${{ github.workspace }}/fe/.type-coverage
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}
